language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - git clone git://github.com/cakephp/cakephp ../cakephp
  - cd ..
  - cp -R cakephp-waltook cakephp/app/Plugin/Waltook
  - chmod -R 777 cakephp/app/tmp
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - echo "<?php
   class DATABASE_CONFIG {
   public \$default = array(
     'datasource' => 'Database/Mysql',
     'database' => 'cakephp_test',
     'host' => '0.0.0.0',
     'login' => 'travis',
     'host' => '',
     'persistent' => false,
   );
   }" > cakephp/app/Config/database.php
   - chmod 777 ./cakephp/app/Plugin/Waltook/Config -R
   - cp cakephp/app/Plugin/PreguntaFrecuente/.coveralls.yml .coveralls.yml
   - composer install --dev
   - mkdir -p build/logs

script:
  - ./cakephp/app/Console/cake test Waltook Controller/Component/SmsComponent --stderr --coverage-clover build/logs/clover-plugin.xml


after_script:
  - cd cakephp-waltook/
  - php ../vendor/bin/coveralls -v
